# -*- coding: utf-8 -*-
"""
/***************************************************************************
 netscan_sabine
                                 A QGIS plugin
 A plugin to load in WFS-layers from TKI and allow measurements to be taken
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-15
        copyright            : (C) 2025 by FTTH D&E
        email                : toon.vandevoorde@jacops.be
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load netscan_sabine class from file netscan_sabine.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .netscan_sabine_module import netscan_sabine
    return netscan_sabine(iface)
