# -*- coding: utf-8 -*-
"""
/***************************************************************************
 netscan_sabine
                                 A QGIS plugin
 A plugin to load in WFS-layers from TKI and allow measurements to be taken
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by FTTH D&E
        email                : toon.vandevoorde@jacops.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtWidgets import QToolBar
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .netscan_sabine_module_dockwidget import netscan_sabineDockWidget
import os.path

ACTION_OBJECT_NAME = 'netscan_sabine_measure_action'

class netscan_sabine:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'netscan_sabine_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Netscan_WFS')
        # TODO: We are going to let the user set this up in a future iteration

        #print "** INITIALIZING netscan_sabine"

        self.pluginIsActive = False
        self.dockwidget = None

        self.jacops_toolbar = self.__jacops_toolbar()

    def __jacops_toolbar(self) -> QToolBar:
        naam = 'Jacops Toolbar'
        main_window = self.iface.mainWindow()
        toolbar = main_window.findChild(QToolBar, naam)
        if toolbar is None:
            toolbar = self.iface.addToolBar(naam)
            toolbar.setObjectName(naam)
        return toolbar

    def add_to_jacops_toolbar(self, icon_path: str, text: str, callback, enabled: bool = True,
                              object_name: str = ACTION_OBJECT_NAME) -> QAction:
        toolbar = self.__jacops_toolbar()

        # reuse existing action if present
        for existing in toolbar.actions():
            if existing.objectName() == object_name or existing.text() == text:
                return existing

        action = QAction(QIcon(icon_path), text, self.iface.mainWindow())
        action.triggered.connect(callback)
        action.setEnabled(enabled)
        action.setObjectName(object_name)
        toolbar.addAction(action)
        self.actions.append(action)

        plugin_dir = self.plugin_dir
        icon_log = os.path.join(plugin_dir, 'icon.png')
        # attempt to prefer a disk icon (e.g. icon.png) and refresh the toolbar widget
        try:
            # adjust filename if your actual disk icon differs
            if os.path.exists(icon_log):
                self.set_action_icon_from_plugin(action, 'icon.png')
        except Exception:
            pass

        return action

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('netscan_sabine', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)


        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # use jacops toolbar for all toolbar additions
            self.__jacops_toolbar().addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)
        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        plugin_dir = os.path.dirname(__file__)
        icon_path = os.path.join(plugin_dir, "icon.png")

        self.add_to_jacops_toolbar(
            icon_path=icon_path,
            text=self.tr(u'Measure with Sabine :)'),
            callback=self.run,
            enabled=True,
            object_name=ACTION_OBJECT_NAME)

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING netscan_sabine"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # remove actions added by this instance
        jacops = self.__jacops_toolbar()
        for a in list(jacops.actions()):
            if a.objectName() == ACTION_OBJECT_NAME or a.text() == self.tr(u'Measure with Sabine :)'):
                jacops.removeAction(a)

    #--------------------------------------------------------------------------
    def run(self):
        """Run method that loads and starts the plugin"""
        if not self.pluginIsActive:
            self.pluginIsActive = True

            # Create the dockwidget if missing, passing explicit canvas
            if self.dockwidget is None:
                self.dockwidget = netscan_sabineDockWidget(parent=self.iface.mainWindow(),
                                                           canvas=self.iface.mapCanvas())
                self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # Ensure a single connection to closingPlugin
            try:
                self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
            except Exception:
                pass
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # Show the dockwidget
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
