# -*- coding: utf-8 -*-
"""
/***************************************************************************
 netscan_sabineDockWidget
                                 A QGIS plugin
 A plugin to load in WFS-layers from TKI and allow measurements to be taken
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by FTTH D&E
        email                : toon.vandevoorde@jacops.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# python
import os
from typing import List, Tuple, Dict, Any, Optional

from PyQt5.QtWidgets import QTextEdit, QTextBrowser
from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtCore import Qt, pyqtSignal
from qgis.PyQt.QtGui import QColor, QIcon

from qgis.core import (
    QgsAuthMethodConfig,
    QgsDataSourceUri,
    QgsVectorLayer,
    QgsProject,
    QgsApplication,
    QgsFeatureRequest,
    QgsGeometry,
    QgsPointXY,
    QgsWkbTypes,
    QgsMessageLog,
    Qgis,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsProject,
    QgsRasterLayer
)

from qgis.core import (
    QgsRuleBasedRenderer,
    QgsSymbol,
    QgsProject,
    QgsCategorizedSymbolRenderer,
    QgsRendererCategory,
    QgsProperty,
    QgsSymbolLayer,
    QgsSimpleLineSymbolLayer


)
from PyQt5.QtGui import QColor, QPixmap
from qgis.gui import QgsMapTool, QgsRubberBand, QgsHighlight


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'netscan_sabine_module_dockwidget_base.ui'))
# Custom display names for specific layers
custom_names = {
    'net_scan_jacops:tc_rl_duct': 'Unifiber - Ducts',
    'net_scan_jacops:tc_rl_segment': 'Unifiber - Segments',
    'net_scan_jacops:tc_rl_scan': 'Unifiber - Scans',
    'net_scan_jacops:tc_rl_structure': 'Unifiber - Structures',
    'net_scan_jacops_wyre:tc_rl_duct': 'Wyre - Ducts',
    'net_scan_jacops_wyre:tc_rl_segment': 'Wyre - Segments',
    'net_scan_jacops_wyre:tc_rl_scan': 'Wyre - Scans',
    'net_scan_jacops_wyre:tc_rl_structure': 'Wyre - Structures',
}
ALLOWED_LAYER_PREFIXES = (
    # Wyre
    "Wyre - Scans",
    "Wyre - Structures",
    "Wyre - Segments",
    "Wyre - Ducts",
    "Proximus - Scans",
    "Proximus - Structures",
    "Proximus - Segments",
    "Proximus - Ducts",
    "Fiberklaar - Scans",
    "Fiberklaar - Structures",
    "Fiberklaar - Segments",
    "Fiberklaar - Ducts",
    "Unifiber - Scans",
    "Unifiber - Structures",
    "Unifiber - Segments",
    "Unifiber - Ducts",
)
STRUCTURE_TYPE_MAP = {
    # 11202: "Grube",
    # 11203: "AZK (Neu)",
    # 11204: "Kabelschacht (Neu)",
    # 11205: "AZK (Bestand)",
    # 11206: "Kabelschacht (Bestand)",
    11209: "POC",
    11210: "EK478",
    11211: "Has-Koppeling",
    11212: "Koppeling",
    11213: "MF endbox",
    11214: "Riser",
    11215: "Toby-Box (type HIB)",
    11216: "Other",
    3906712: "EK578",
    3906715: "Modulaire Betonbak",
    3906716: "Kunstof-lasput (type LOT)",
    3906722: "Handhole (POC)",
    3906723: "Medium Bak (DP)",
    3906724: "Standard Bak (PDP)",
    4962341: "STOP",
    4962342: "Koppelbak",
    4962343: "PDP Beton",
    4962344: "Sokkel POP",
    4962345: "PDP Kunststof",
    4962346: "POC versterkt",
    4962347: "Sokkelpop",
}

STRUCTURE_COLORS = {
    # 11202: QColor("#1f78b4"),   # Grube
    # 11203: QColor("#33a02c"),   # AZK (Neu)
    # 11204: QColor("#e31a1c"),   # Kabelschacht (Neu)
    # 11205: QColor("#6a3d9a"),   # AZK (Bestand)
    # 11206: QColor("#ff7f00"),   # Kabelschacht (Bestand)
    11209: QColor("#b15928"),   # POC
    11210: QColor("#a6cee3"),   # EK478
    11211: QColor("#fb9a99"),   # Has-Koppeling
    11212: QColor("#fdbf6f"),   # Koppeling
    11213: QColor("#cab2d6"),   # MF endbox
    11214: QColor("#ffff99"),   # Riser
    11215: QColor("#8dd3c7"),   # Toby-Box (type HIB)
    11216: QColor("#fccde5"),   # Other
    3906712: QColor("#d9d9d9"), # EK578
    3906715: QColor("#bc80bd"), # Modulaire Betonbak
    3906716: QColor("#ccebc5"), # Kunstof-lasput (type LOT)
    3906722: QColor("#ffed6f"), # Handhole (POC)
    3906723: QColor("#66c2a5"), # Medium Bak (DP)
    3906724: QColor("#fc8d62"), # Standard Bak (PDP)
    4962341: QColor("#8da0cb"), # STOP
    4962342: QColor("#e78ac3"), # Koppelbak
    4962343: QColor("#a6d854"), # PDP Beton
    4962344: QColor("#ffd92f"), # Sokkel POP
    4962345: QColor("#e5c494"), # PDP Kunststof
    4962346: QColor("#b3b3b3"), # POC versterkt
    4962347: QColor("#ff7f7f"), # Sokkelpop
}

# Map provider names to WFS URLs and typenames
WFS_SERVICES = {
    "FIBERKLAAR": {
        "url": "https://scan.tki-chemnitz.de/geoserver/net_scan_fiberklaar/wfs",
        "typenames": ["net_scan_fiberklaar:fiberklaar_layer"],
        "auth_name": "fiberklaar_auth"
    },
    "UNIFIBER": {
        "url": "https://mobile-mapping.tki-chemnitz.de/geoserver/net_scan_jacops/wfs",
        "typenames": [
            "net_scan_jacops:tc_rl_duct",
            "net_scan_jacops:tc_rl_segment",
            "net_scan_jacops:tc_rl_scan",
            "net_scan_jacops:tc_rl_structure"
        ],
        "auth_name": "UNIFIBER TKI"
    },
    "WYRE": {
        "url": "https://mobile-mapping.tki-chemnitz.de/geoserver/net_scan_jacops_wyre/wfs",
        "typenames": [
            "net_scan_jacops_wyre:tc_rl_duct",
            "net_scan_jacops_wyre:tc_rl_segment",
            "net_scan_jacops_wyre:tc_rl_scan",
            "net_scan_jacops_wyre:tc_rl_structure"
        ],
        "auth_name": "TKI WYRE"
    },
    "PROXIMUS": {
        "url": "https://scan.tki-chemnitz.de/geoserver/net_scan_proximus/wfs",
        "typenames": ["net_scan_proximus:proximus_layer"],
        "auth_name": "proximus_auth"
    }
}
DUCT_COLORS = {
    # DB series
    "DB1": QColor("#1f78b4"),      # blue
    "DB2": QColor("#33a02c"),      # green
    "DB4": QColor("#e31a1c"),      # red
    "DB6": QColor("#6a3d9a"),      # purple
    "DB7": QColor("#ff7f00"),      # orange (generic DB7)
    "DB7-Grijs": QColor("gray"),
    "DB7-Oranje": QColor("orange"),
    "DB24": QColor("#b2df8a"),     # light green

    # MF series
    "MF12": QColor("#a6cee3"),     # light blue
    "MF24": QColor("#fb9a99"),     # light red

    # Materials
    "HDPE": QColor("#000000"),     # black
    "PE26": QColor("#b15928"),     # brown
}

STRUCTURE_COLORS = {
    # 11202: QColor("#e6194b"),  # Grube
    # 11203: QColor("#3cb44b"),  # AZK (Neu)
    # 11204: QColor("#ffe119"),  # Kabelschacht (Neu)
    # 11205: QColor("#0082c8"),  # AZK (Bestand)
    # 11206: QColor("#f58231"),  # Kabelschacht (Bestand)
    11209: QColor("#911eb4"),  # POC
    11210: QColor("#46f0f0"),  # EK478
    11211: QColor("#f032e6"),  # Has-Koppeling
    11212: QColor("#d2f53c"),  # Koppeling
    11213: QColor("#fabebe"),  # MF endbox
    11214: QColor("#008080"),  # Riser
    11215: QColor("#e6beff"),  # Toby-Box (type HIB)
    11216: QColor("#aa6e28"),  # Other
    3906712: QColor("#fffac8"), # EK578
    3906715: QColor("#800000"), # Modulaire Betonbak
    3906716: QColor("#aaffc3"), # Kunstof-lasput (type LOT)
    3906722: QColor("#808000"), # Handhole (POC)
    3906723: QColor("#ffd8b1"), # Medium Bak (DP)
    3906724: QColor("#000075"), # Standard Bak (PDP)
    4962341: QColor("#808080"), # STOP
    4962342: QColor("#ffffff"), # Koppelbak
    4962343: QColor("#000000"), # PDP Beton
    4962344: QColor("#bcf60c"), # Sokkel POP
    4962345: QColor("#ffaeb9"), # PDP Kunststof
    4962346: QColor("#baffc9"), # POC versterkt
    4962347: QColor("#xfffacd"), # Sokkelpop
}

SYNERGIE_VALUES = [
    'SYNERGIE WYRE',
    'SYNERGIE FIBERKLAAR',
    'SYNERGIE PROXIMUS',
    'SYNERGIE AUTRE',
    'SYNERGIE UNIFIBER',
    'SYNERGIE BLA'
]


# Suppose your combo box is self.mComboBox
# icons = {
#     "FIBERKLAAR": ":fiberklaarlogo.png",
#     "UNIFIBER": ":/icons/unifiber.png",
#     "WYRE": ":/icons/wyre.png",
#     "PROXIMUS": ":/icons/proximus.png",
# }
def extract_wfs_typename(layer: QgsVectorLayer) -> Optional[str]:
    try:
        src = layer.source()
        for part in src.split("&"):
            if part.lower().startswith("typename="):
                return part.split("=", 1)[1]
    except Exception:
        pass
    return None


# python
def style_wfs_layer(layer: QgsVectorLayer):
    if not isinstance(layer, QgsVectorLayer) or not layer.isValid():
        return

    geom_type = layer.geometryType()
    layer_name = layer.name().upper()

    # SEGMENT styling (categorized by c_synergie)
    if "SEGMENT" in layer_name:
        categories = []

        for synergy in SYNERGIE_VALUES:
            sym = QgsSymbol.defaultSymbol(geom_type)

            line_layer = QgsSimpleLineSymbolLayer()
            line_layer.setColor(QColor("red"))
            line_layer.setWidth(1.5)

            line_layer.setDataDefinedProperty(
                QgsSymbolLayer.PropertyStrokeStyle,
                QgsProperty.fromExpression(
                    "CASE WHEN \"id_segment_type\" = 3 THEN 'dash' ELSE 'solid' END"
                )
            )

            sym.changeSymbolLayer(0, line_layer)

            # Correct order: (value, symbol, label)
            categories.append(
                QgsRendererCategory(synergy, sym, f"Synergy ({synergy})")
            )

        # Non-synergy segments
        sym_gray = QgsSymbol.defaultSymbol(geom_type)

        gray_layer = QgsSimpleLineSymbolLayer()
        gray_layer.setColor(QColor("gray"))
        gray_layer.setWidth(0.8)

        gray_layer.setDataDefinedProperty(
            QgsSymbolLayer.PropertyStrokeStyle,
            QgsProperty.fromExpression(
                "CASE WHEN \"id_segment_type\" = 3 THEN 'dash' ELSE 'solid' END"
            )
        )

        sym_gray.changeSymbolLayer(0, gray_layer)

        categories.append(
            QgsRendererCategory("NON_SYNERGY", sym_gray, "Non-synergy")
        )

        renderer = QgsCategorizedSymbolRenderer("c_synergie", categories)
        renderer.setClassAttribute(
            "CASE WHEN \"c_synergie\" IS NULL OR \"c_synergie\" = 'Non' "
            "THEN 'NON_SYNERGY' ELSE \"c_synergie\" END"
        )

        layer.setRenderer(renderer)
        layer.triggerRepaint()

    # DUCT styling (categorized by Feature + c_synergie)
    elif "DUCT" in layer_name:
        name_field = "name"
        categories = []

        unique_names = sorted({
            f[name_field]
            for f in layer.getFeatures()
            if f[name_field] is not None
        })

        for name in unique_names:
            color = DUCT_COLORS.get(name, QColor("gray"))

            sym = QgsSymbol.defaultSymbol(geom_type)
            sym.setColor(color)

            if geom_type == QgsWkbTypes.LineGeometry:
                sym.setWidth(1.0)
            elif geom_type == QgsWkbTypes.PointGeometry:
                sym.setSize(2.0)

            # Correct order: (value, symbol, label)
            categories.append(
                QgsRendererCategory(name, sym, str(name))
            )

        # NULL / unknown ducts
        sym_gray = QgsSymbol.defaultSymbol(geom_type)
        sym_gray.setColor(QColor("gray"))
        categories.append(
            QgsRendererCategory(None, sym_gray, "Unknown duct")
        )

        renderer = QgsCategorizedSymbolRenderer(name_field, categories)
        layer.setRenderer(renderer)
        layer.triggerRepaint()

    # STRUCTURE styling (single green symbol)
    elif "STRUCTURE" in layer_name:
        fid_type_field = "fid_type"
        categories = []

        for fid, color in STRUCTURE_COLORS.items():
            sym = QgsSymbol.defaultSymbol(geom_type)
            sym.setColor(color)
            if geom_type == QgsWkbTypes.LineGeometry:
                sym.setWidth(1.0)
            elif geom_type == QgsWkbTypes.PointGeometry:
                sym.setSize(2.0)
            # Correct order: (value, symbol, label)
            categories.append(QgsRendererCategory(fid, sym, STRUCTURE_TYPE_MAP.get(fid, str(fid))))

        # Unknown types
        sym_gray = QgsSymbol.defaultSymbol(geom_type)
        sym_gray.setColor(QColor("gray"))
        categories.append(QgsRendererCategory(None, sym_gray, "Unknown"))

        renderer = QgsCategorizedSymbolRenderer(fid_type_field, categories)
        layer.setRenderer(renderer)
        layer.triggerRepaint()

def _layer_display_name(layer) -> Optional[str]:
    """Return a usable display name for a QGIS layer (calls .name() if callable)."""
    try:
        if layer is None:
            return None
        # prefer the callable .name()
        name_attr = getattr(layer, "name", None)
        if callable(name_attr):
            try:
                return name_attr()
            except Exception:
                pass
        # if name attribute exists but is not callable, convert to string
        if name_attr is not None:
            return str(name_attr)
        # fallback to source or id
        src = getattr(layer, "source", None)
        if callable(src):
            try:
                return src()
            except Exception:
                pass
        if src is not None:
            return str(src)
    except Exception:
        pass
    return None


def get_auth_id_for_provider(provider_name: str) -> Optional[str]:
    """
    Return the QGIS AuthConfig ID for a given provider name,
    based on the name stored in QGIS Auth Manager.
    """
    EXPECTED_AUTH_NAMES = {
        "FIBERKLAAR": "TKI FIBERKLAAR",
        "UNIFIBER": "UNIFIBER TKI",
        "WYRE": "TKI WYRE",
        "PROXIMUS": "UNIFIBER TKI",
    }

    auth_name = EXPECTED_AUTH_NAMES.get(provider_name.upper())
    if not auth_name:
        return None

    auth_mgr = QgsApplication.authManager()

    # `availableAuthMethodConfigs()` returns {authcfg_id: QgsAuthMethodConfig}
    configs = auth_mgr.availableAuthMethodConfigs()

    for auth_id, cfg in configs.items():
        if cfg.name() == auth_name:
            return auth_id

    return None

class netscan_sabineDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    closingPlugin = pyqtSignal()

    def __init__(self, parent=None, canvas=None):

        super().__init__(parent)

        # Explicit canvas must be passed
        if canvas is None:
            raise ValueError("You must pass a valid QgsMapCanvas to the dock widget")
        self.canvas = canvas
        self.dock = self  # <-- ADD THIS LINE

        self.prev_map_tool = None
        self.polygon_tool = None


        self.prev_map_tool = None
        self.polygon_tool = None
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.txtUnifiber = self.findChild(QtWidgets.QTextBrowser, "txtUnifiber")
        if self.txtUnifiber is None:
            print(">>> ERROR: txtUnifiber not found in UI")
        else:
            self.txtUnifiber.clear()
            self.txtUnifiber.append("Draw a polygon to analyze data and see results...")
            print(">>> txtUnifiber (QTextBrowser) successfully initialized")

        plugin_dir = os.path.dirname(__file__)
        pxm_logo = os.path.join(plugin_dir, "proximuslogo.png")

        plugin_dir = os.path.dirname(__file__)
        wyre_logo = os.path.join(plugin_dir, "wyre-logo.png")

        plugin_dir = os.path.dirname(__file__)
        unifiber_logo = os.path.join(plugin_dir, "unifiberlogo.png")

        plugin_dir = os.path.dirname(__file__)
        fiberklaar_logo = os.path.join(plugin_dir, "fiberklaarlogo.png")
        # --- Providers and icons ---


        providers = [
            ("FIBERKLAAR", fiberklaar_logo),  # local icon in plugin dir
            ("UNIFIBER", unifiber_logo),
            ("WYRE", wyre_logo),
            ("PROXIMUS", pxm_logo),
        ]
        # Clear combo box first
        self.mComboBox.clear()
        for name, icon_path in providers:
            self.mComboBox.addItem(name)
            idx = self.mComboBox.count() - 1
            item = self.mComboBox.model().item(idx, 0)

            if item:
                item.setCheckable(True)
                item.setCheckState(0)
                item.setIcon(QIcon(icon_path))

                if name in ["FIBERKLAAR", "PROXIMUS"]:
                    item.setForeground(QColor("gray"))

                    font = item.font()
                    font.setStrikeOut(True)
                    item.setFont(font)

        plugin_dir = os.path.dirname(__file__)
        layers_icon_path = os.path.join(plugin_dir, "layers.png")

        if hasattr(self, "btn_lagen_inladen"):
            # Set icon (fallback to a standard icon if file missing or fails)
            if os.path.exists(layers_icon_path):
                try:
                    self.btn_lagen_inladen.setIcon(QIcon(layers_icon_path))
                except Exception:
                    self.btn_lagen_inladen.setIcon(self.style().standardIcon(QtWidgets.QStyle.SP_DialogOpenButton))
            else:
                self.btn_lagen_inladen.setIcon(self.style().standardIcon(QtWidgets.QStyle.SP_DialogOpenButton))

            # Optional: tooltip and accessible name
            self.btn_lagen_inladen.setToolTip("Load layers")
            self.btn_lagen_inladen.setAccessibleName("btn_load_layers")

            # Connect handler
            self.btn_lagen_inladen.clicked.connect(self.load_selected_layers)
        # python
        plugin_dir = os.path.dirname(__file__)
        pencil_icon_path = os.path.join(plugin_dir, "pencil.png")

        if hasattr(self, "btn_select"):
            # Set icon (fallback to a standard icon if file missing or fails)
            if os.path.exists(pencil_icon_path):
                try:
                    self.btn_select.setIcon(QIcon(pencil_icon_path))
                except Exception:
                    self.btn_select.setIcon(self.style().standardIcon(QtWidgets.QStyle.SP_DialogOpenButton))
            else:
                self.btn_select.setIcon(self.style().standardIcon(QtWidgets.QStyle.SP_DialogOpenButton))

            # Optional: tooltip and accessible name
            self.btn_select.setToolTip("Select polygon")
            self.btn_select.setAccessibleName("btn_select_polygon")

            # Connect handler
            self.btn_select.clicked.connect(self.activate_polygon_selection)

        plugin_dir = os.path.dirname(__file__)
        searching_icon_path = os.path.join(plugin_dir, "info.png")

        if os.path.exists(searching_icon_path):
            self.btn_info.setIcon(QIcon(searching_icon_path))
        else:
            self.btn_info.setIcon(self.style().standardIcon(QtWidgets.QStyle.SP_MessageBoxInformation))

        # Tooltip (optional)
        self.btn_info.setToolTip("Info")

        # Connect
        self.btn_info.clicked.connect(self.show_info_message)

    def add_layer_wms(self):

        tms = 'type=xyz&url=https://tile.openstreetmap.org/{z}/{x}/{y}.png&zmax=19&zmin=0'
        layer_name = 'OSM'

        # avoid duplicates
        if QgsProject.instance().mapLayersByName(layer_name):
            QgsMessageLog.logMessage("OSM layer already exists, skipping.", "netscan_sabine", Qgis.Info)
            return

        slayer = QgsRasterLayer(tms, layer_name, 'wms')
        if not slayer.isValid():
            QgsMessageLog.logMessage("Failed to create OSM layer (invalid).", "netscan_sabine", Qgis.Warning)
            return

        # register the layer without adding it to the layer tree
        QgsProject.instance().addMapLayer(slayer, False)

        root = QgsProject.instance().layerTreeRoot()
        try:
            # insert at the bottom (so other layers added later appear above it)
            root.insertLayer(len(root.children()), slayer)
            QgsMessageLog.logMessage("OSM layer added at bottom of layer tree.", "netscan_sabine", Qgis.Info)
        except Exception as ex:
            # fallback: add normally if insert fails
            QgsProject.instance().addMapLayer(slayer)
            QgsMessageLog.logMessage(f"Insert at bottom failed ({ex}); added normally.", "netscan_sabine", Qgis.Warning)



    def show_info_message(self):
        """Show plugin info message box with searching.png as icon."""

        msg = QtWidgets.QMessageBox(self)
        msg.setWindowTitle("Netscan Sabine - Info")

        msg.setInformativeText(
            "This plugin loads WFS layers from TKI for asbuilt data.\n\n"
            "⚠️ Important: Make sure the following authentication configurations exist in QGIS:\n\n"
            "• UNIFIBER → UNIFIBER TKI\n"
            "• WYRE → TKI WYRE\n"
            "• Proximus and Fiberklaar are not available yet\n\n"
            "If these auth configurations are missing or named differently, the WFS layers will not load."
        )

        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg.exec()

    def activate_polygon_selection(self):
        if getattr(self, "polygon_tool", None):
            try:
                self.polygon_tool.clear_highlights()
                self.polygon_tool.reset()
                self.polygon_tool.deactivate()
            except Exception:
                pass
            try:
                if getattr(self.polygon_tool, "prev_map_tool", None):
                    self.canvas.setMapTool(self.polygon_tool.prev_map_tool)
            except Exception:
                pass
        # Resolve stored layers or attempt auto-detect
        seg_layer = getattr(self, "segment_layer", None)
        duct_layer = getattr(self, "duct_layer", None)
        struct_layer = getattr(self, "structure_layer", None)

        if not isinstance(seg_layer, QgsVectorLayer) or seg_layer is None or not seg_layer.isValid() \
                or not isinstance(duct_layer, QgsVectorLayer) or duct_layer is None or not duct_layer.isValid() \
                or (struct_layer is not None and (
                not isinstance(struct_layer, QgsVectorLayer) or not struct_layer.isValid())):
            for lyr in QgsProject.instance().mapLayers().values():
                try:
                    if not isinstance(lyr, QgsVectorLayer):
                        continue
                    lname = lyr.name().lower()
                    if seg_layer is None and "segment" in lname:
                        seg_layer = lyr
                    if duct_layer is None and "duct" in lname:
                        duct_layer = lyr
                    if struct_layer is None and lyr.geometryType() == QgsWkbTypes.PointGeometry and "structure" in lname:
                        struct_layer = lyr
                    if seg_layer is not None and duct_layer is not None and struct_layer is not None:
                        break
                except Exception:
                    continue

        # store resolved layers
        self.segment_layer = seg_layer
        self.duct_layer = duct_layer
        self.structure_layer = struct_layer

        QgsMessageLog.logMessage(
            f"activate_polygon_selection: segment_layer={_layer_display_name(seg_layer) or repr(seg_layer)}, "
            f"duct_layer={_layer_display_name(duct_layer) or repr(duct_layer)}, "
            f"structure_layer={_layer_display_name(struct_layer) or repr(struct_layer)}",
            "netscan_sabine",
            level=Qgis.Info
        )

        # Create and activate PolygonSelectTool, pass the dock's text widget reference so the tool doesn't try to find or reparent UI
        try:
            self.polygon_tool = PolygonSelectTool(
                canvas=self.canvas,
                segment_layer_id=seg_layer.id() if seg_layer else None,
                duct_layer_id=duct_layer.id() if duct_layer else None,
                structure_layer_id=struct_layer.id() if struct_layer else None,
                on_found=self.on_polygon_found,
                txt_unifiber=self.txtUnifiber,
                btn_select=self.btn_select  # <-- pass button here
            )

            # preserve previous tool and set new map tool
            try:
                self.prev_map_tool = self.canvas.mapTool()
                self.polygon_tool.prev_map_tool = self.prev_map_tool
                self.canvas.setMapTool(self.polygon_tool)
            except Exception:
                QgsMessageLog.logMessage("Failed to set polygon map tool", "netscan_sabine", level=Qgis.Warning)

            # preserve previous tool and set new map tool
            try:
                self.prev_map_tool = self.canvas.mapTool()
                self.polygon_tool.prev_map_tool = self.prev_map_tool
            except Exception:
                self.prev_map_tool = None
            try:
                self.canvas.setMapTool(self.polygon_tool)
                # Change button color to indicate selection active
                self.btn_select.setStyleSheet("background-color: lightgreen;")  # or any color you like

            except Exception:
                QgsMessageLog.logMessage("Failed to set polygon map tool", "netscan_sabine", level=Qgis.Warning)
        except Exception as ex:
            QgsMessageLog.logMessage(f"Failed to create PolygonSelectTool: {ex}", "netscan_sabine", level=Qgis.Warning)


    def closeEvent(self, event):
        """Emit closingPlugin and call base handler."""
        try:
            self.closingPlugin.emit()
        except Exception:
            pass
        try:
            super().closeEvent(event)
        except Exception:
            event.accept()

    # python
    def classify_layer(self, layer: QgsVectorLayer) -> Tuple[Optional[str], Optional[str]]:
        """
        Return (provider, layer_type) based on layer name or WFS typename.
        """
        if layer is None or not isinstance(layer, QgsVectorLayer):
            return None, None

        lname = layer.name().lower()
        provider = None
        layer_type = None

        # Provider detection
        if "unifiber" in lname or "net_scan_jacops:" in lname:
            provider = "UNIFIBER"
        elif "wyre" in lname or "net_scan_jacops_wyre:" in lname:
            provider = "WYRE"
        elif "fiberklaar" in lname or "net_scan_fiberklaar:" in lname:
            provider = "FIBERKLAAR"
        elif "proximus" in lname or "net_scan_proximus:" in lname:
            provider = "PROXIMUS"

        # Layer type detection
        if "duct" in lname:
            layer_type = "DUCT"
        elif "structure" in lname:
            layer_type = "STRUCTURE"
        elif "segment" in lname:
            layer_type = "SEGMENT"
        elif "scan" in lname:
            layer_type = "SCAN"

        # Fallback: try WFS typename if layer_type is still unknown
        if layer_type is None:
            src = getattr(layer, "source", "")
            if isinstance(src, str):
                if "duct" in src.lower():
                    layer_type = "DUCT"
                elif "structure" in src.lower():
                    layer_type = "STRUCTURE"
                elif "segment" in src.lower():
                    layer_type = "SEGMENT"
                elif "scan" in src.lower():
                    layer_type = "SCAN"
                else:
                    layer_type = "UNKNOWN"

        if provider is None:
            provider = "UNKNOWN"

        return provider, layer_type


    def on_polygon_found(self, summary):
        text_widget = getattr(self, "txtUnifiber", None)
        if text_widget is None:
            print(">>> ERROR: txtUnifiber not initialized!")
            return

        text_widget.clear()

        if not summary:
            text_widget.append("<i>No features found in polygon.</i>")
            return

        # Group summary by provider
        provider_dict = {}
        for key, info in summary.items():
            provider = info.get("provider", "UNKNOWN")
            layer_type = info.get("layer_type", "UNKNOWN")
            details = info.get("details", {})
            provider_dict.setdefault(provider, {})[layer_type] = details

        for provider, layers in provider_dict.items():
            # Provider header
            text_widget.append(f'<b style="font-size:12pt; color:#2A52BE;">{provider}</b>')

            for layer_type in ["SEGMENT", "DUCT", "STRUCTURE", "SCAN", "None"]:
                if layer_type not in layers:
                    continue

                details = layers[layer_type]

                # Layer type header
                text_widget.append(f'<b style="color:#228B22;">{layer_type}</b>')

                if not details:
                    text_widget.append('<i style="margin-left:10px;">(no features)</i>')
                    continue

                # List features inline but block style to control spacing
                for fid, val in details.items():
                    if layer_type == "DUCT":
                        text_widget.append(
                            f'<span style="display:block; margin-left:10px;">{fid}: {float(val):.2f} m</span>')
                    else:
                        text_widget.append(f'<span style="display:block; margin-left:10px;">{fid}: {int(val)}</span>')

            # Optional small separator
            text_widget.append('<br>')

    def _checked_provider_names(self) -> list:
        """Return list of provider names checked in the UI, robust to widget type."""
        combo = getattr(self, 'mComboBox', None)
        if combo is None:
            return []

        names = []
        # preferred API
        if hasattr(combo, 'checkedItems'):
            try:
                for it in combo.checkedItems():
                    names.append(str(it))
                return names
            except Exception:
                pass

        # fallback: iterate items and inspect check state
        try:
            count = combo.count()
        except Exception:
            return names

        for i in range(count):
            checked = False
            if hasattr(combo, 'itemChecked'):
                try:
                    checked = combo.itemChecked(i)
                except Exception:
                    checked = False
            if not checked:
                try:
                    index = combo.model().index(i, 0)
                    checked = (index.data(Qt.CheckStateRole) == Qt.Checked)
                except Exception:
                    checked = False
            if not checked:
                continue

            try:
                text = combo.itemText(i)
            except Exception:
                try:
                    text = combo.model().index(i, 0).data(Qt.DisplayRole)
                except Exception:
                    text = ''
            if text:
                names.append(str(text))
        return names

    # python
    def load_selected_layers(self):
        # (existing provider selection and uri setup code unchanged)
        checked_items = self.mComboBox.checkedItems()
        if not checked_items:
            QtWidgets.QMessageBox.information(self, "Load layers", "No providers selected.")
            return


        for provider in checked_items:
            provider_upper = provider.upper()
            if provider_upper not in WFS_SERVICES:
                continue

            svc = WFS_SERVICES[provider_upper]
            url = svc["url"]
            auth_id = get_auth_id_for_provider(provider_upper)

            for typename in svc["typenames"]:
                uri = QgsDataSourceUri()
                uri.setParam("service", "WFS")
                uri.setParam("version", "2.0.0")
                uri.setParam("request", "GetFeature")
                uri.setParam("typename", typename)
                uri.setParam("srsName", "EPSG:31370")
                uri.setParam("url", url)
                if auth_id:
                    uri.setAuthConfigId(auth_id)

                # Use custom display name when available
                layer_name = custom_names.get(typename, typename.split(":")[-1])
                try:
                    vl = QgsVectorLayer(uri.uri(), layer_name, "WFS")
                    if not vl.isValid():
                        QtWidgets.QMessageBox.warning(self, "Load WFS", f"Failed to load {layer_name}")
                    else:
                        QgsProject.instance().addMapLayer(vl)
                        # Immediately style the layer
                        style_wfs_layer(vl)
                except Exception as e:
                    QtWidgets.QMessageBox.warning(self, "Load WFS", f"Error loading {layer_name}: {e}")
        try:
            # Ensure base map is added after WFS layers
            self.add_layer_wms()
        except Exception:
            pass

        QtWidgets.QMessageBox.information(self, "Load WFS", "Finished loading selected layers.")

# python
class PolygonSelectTool(QgsMapTool):

    def __init__(
            self,
            canvas,
            segment_layer_id=None,
            duct_layer_id=None,
            structure_layer_id=None,
            on_found=None,
            txt_unifiber=None,
            btn_select=None

    ):
        super().__init__(canvas)
        self.canvas = canvas

        self.segment_layer_id = segment_layer_id
        self.duct_layer_id = duct_layer_id
        self.structure_layer_id = structure_layer_id
        self.btn_select = btn_select  # <-- store button reference
        self.on_found = on_found
        self.txtUnifiber = txt_unifiber

        # Use the text widget passed by the dock; do NOT try to find UI children on the tool
        self.txtUnifiber: Optional[QTextBrowser] = txt_unifiber
        if self.txtUnifiber is None:
            # don't try to create or reparent the widget here; dock owns UI
            print(">>> INFO: PolygonSelectTool: no txtUnifiber reference provided")
        else:
            try:
                self.txtUnifiber.append("Polygon tool activated")
            except Exception:
                pass

        # drawing state
        self.drawing = False
        self.points: List[QgsPointXY] = []

        self.rubber = None
        try:
            self.rubber = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
            self.rubber.setColor(QColor(255, 0, 0, 100))
            self.rubber.setWidth(2)
        except Exception:
            self.rubber = None

        self.prev_map_tool = None
        self.highlights: List[Any] = []


    def canvasPressEvent(self, event):
        pt = self.toMapCoordinates(event.pos())
        if event.button() == Qt.LeftButton:
            if not self.drawing:
                self.drawing = True
                self.points = []
                try:
                    self.rubber.reset(QgsWkbTypes.PolygonGeometry)
                except TypeError:
                    try:
                        self.rubber.reset()
                    except Exception:
                        pass
                except Exception:
                    try:
                        self.rubber.reset(True)
                    except Exception:
                        pass
            self.points.append(pt)
            try:
                self.rubber.addPoint(pt, True)
            except TypeError:
                try:
                    self.rubber.addPoint(pt)
                except Exception:
                    pass
        elif event.button() == Qt.RightButton and self.drawing:
            self.finish_polygon()

    def canvasMoveEvent(self, event):
        if not self.drawing:
            return
        pt = self.toMapCoordinates(event.pos())
        try:
            self.rubber.reset(QgsWkbTypes.PolygonGeometry)
        except TypeError:
            try:
                self.rubber.reset()
            except Exception:
                pass
        except Exception:
            try:
                self.rubber.reset(True)
            except Exception:
                pass
        for p in self.points:
            try:
                self.rubber.addPoint(p, True)
            except TypeError:
                try:
                    self.rubber.addPoint(p)
                except Exception:
                    pass
        try:
            self.rubber.addPoint(pt, True)
        except TypeError:
            try:
                self.rubber.addPoint(pt)
            except Exception:
                pass

    def finish_polygon(self):
        print(">>> finish_polygon CALLED")
        QgsMessageLog.logMessage("finish_polygon CALLED", "netscan_sabine", Qgis.Info)
        segment_layer = self._layer_from_id(self.segment_layer_id)
        duct_layer = self._layer_from_id(self.duct_layer_id)
        structure_layer = self._layer_from_id(self.structure_layer_id)
        #
        SEGMENT_TYPE_MAP = {
            1: "Open sleuf",
            2: "Handboring",
            3: "Gestuurde boring",
        }
        STRUCTURE_TYPE_MAP = {
            # 11202: "Grube",
            # 11203: "AZK (Neu)",
            # 11204: "Kabelschacht (Neu)",
            # 11205: "AZK (Bestand)",
            # 11206: "Kabelschacht (Bestand)",
            11209: "POC",
            11210: "EK478",
            11211: "Has-Koppeling",
            11212: "Koppeling",
            11213: "MF endbox",
            11214: "Riser",
            11215: "Toby-Box (type HIB)",
            11216: "Other",
            3906712: "EK578",
            3906715: "Modulaire Betonbak",
            3906716: "Kunstof-lasput (type LOT)",
            3906722: "Handhole (POC)",
            3906723: "Medium Bak (DP)",
            3906724: "Standard Bak (PDP)",
            4962341: "STOP",
            4962342: "Koppelbak",
            4962343: "PDP Beton",
            4962344: "Sokkel POP",
            4962345: "PDP Kunststof",
            4962346: "POC versterkt",
            4962347: "Sokkelpop",
        }

        if len(self.points) < 3:
            print(">>> Not enough points to form polygon")
            self.reset()
            return

        # Close polygon
        pts = list(self.points)
        if pts[0] != pts[-1]:
            pts.append(pts[0])
        poly = QgsGeometry.fromPolygonXY([pts])
        map_crs = self.canvas.mapSettings().destinationCrs()

        summary: dict[str, dict] = {}

        # Collect candidate layers
        candidate_layers = []

        explicit_layers = [segment_layer, duct_layer, structure_layer]
        for el in explicit_layers:
            if isinstance(el, QgsVectorLayer):
                candidate_layers.append(el)

        ALLOWED_LAYER_KEYWORDS = ("unifiber", "wyre", "fiberklaar", "proximus")

        for lyr in QgsProject.instance().mapLayers().values():
            if not isinstance(lyr, QgsVectorLayer) or not lyr.isValid():
                continue

            lname = lyr.name().lower().strip()
            if not any(keyword in lname for keyword in ALLOWED_LAYER_KEYWORDS):
                continue

            if lyr not in candidate_layers:
                candidate_layers.append(lyr)

            QgsMessageLog.logMessage(
                f"Accepted layer: {lyr.name()}",
                "netscan_sabine",
                Qgis.Info
            )

        if not candidate_layers:
            print(">>> No candidate layers found")
            if self.on_found:
                self.on_found(summary)
            self.reset()
            return

        # Process layers
        for layer in candidate_layers:
            if not isinstance(layer, QgsVectorLayer) or not layer.isValid():
                continue

            provider, layer_type = getattr(self, 'classify_layer', lambda l: (None, None))(layer)

            # --- FALLBACK detection based on layer name ---
            if provider is None:
                provider = layer.name().split()[0]  # e.g., 'Wyre', 'Fiberklaar', etc.
            if layer_type is None:
                lname = layer.name().lower()
                if lname.startswith("UNKNOWN"):
                    continue
                elif "duct" in lname:
                    layer_type = "DUCT"
                elif "structure" in lname:
                    layer_type = "STRUCTURE"
                elif "segment" in lname:
                    layer_type = "SEGMENT"


            key = f"{provider}:{layer_type}"
            if key not in summary:
                summary[key] = {"provider": provider, "layer_type": layer_type, "details": {}}
            details = summary[key]["details"]

            # Transform polygon to layer CRS if needed
            check_poly = QgsGeometry(poly)
            try:
                if map_crs != layer.crs():
                    transform = QgsCoordinateTransform(map_crs, layer.crs(), QgsProject.instance())
                    check_poly.transform(transform)
            except Exception as e:
                QgsMessageLog.logMessage(f"{layer.name()}: CRS transform failed: {e}", "netscan_sabine", Qgis.Warning)
                continue

            # Fetch features intersecting polygon
            try:
                request = QgsFeatureRequest().setFilterRect(check_poly.boundingBox())
                features = list(layer.getFeatures(request))
            except Exception:
                features = list(layer.getFeatures())

            for f in features:
                geom = f.geometry()
                if not geom:
                    continue
                try:
                    if not geom.intersects(check_poly):
                        continue
                except Exception:
                    continue
                # -----------------------
                # HIGHLIGHT FEATURE
                # -----------------------
                if layer_type == "SEGMENT":
                    # Red, dashed crossings are already styled → thicker highlight
                    is_crossing = (
                            "id_segment_type" in f.fields().names()
                            and f["id_segment_type"] == 3
                    )
                    self.highlight_feature(
                        layer,
                        f,
                        QColor(255, 0, 0, 180),
                        width=4 if is_crossing else 2
                    )

                elif layer_type == "DUCT":
                    self.highlight_feature(
                        layer,
                        f,
                        QColor(0, 0, 255, 180),
                        width=2
                    )

                elif layer_type == "STRUCTURE":
                    self.highlight_feature(
                        layer,
                        f,
                        QColor(0, 180, 0, 200),
                        width=4
                    )
                # --- accumulate totals ---
                if layer_type == "DUCT":
                    name = next(
                        (f[field] for field in ["name", "duct_name", "id", "fid"] if field in f.fields().names()),
                        "UNKNOWN")
                    details[name] = details.get(name, 0.0) + float(geom.length())
                elif layer_type == "STRUCTURE":


                    field_name = None
                    for candidate in ("fid_type", "structure_type", "id"):
                        if candidate in f.fields().names():
                            field_name = candidate
                            break

                    if field_name:
                        raw = f[field_name]
                        try:
                            raw_int = int(raw)
                        except Exception:
                            raw_int = None

                        label = STRUCTURE_TYPE_MAP.get(raw_int, f"UNKNOWN ({raw})")
                    else:
                        if label.startswith("UNKNOWN"):
                            continue
                    details[label] = details.get(label, 0) + 1

                elif layer_type == "SEGMENT":
                    if "id_segment_type" in f.fields().names():
                        raw = f["id_segment_type"]
                        label = SEGMENT_TYPE_MAP.get(raw, f"UNKNOWN ({raw})")
                    else:
                        label = "UNKNOWN"

                    details[label] = details.get(label, 0) + 1

                else:
                    fid = str(f.id())
                    details[fid] = details.get(fid, 0) + 1

        # Callback with results
        if self.on_found:
            try:
                self.on_found(summary)
            except Exception:
                QgsMessageLog.logMessage("on_found callback failed", "netscan_sabine", Qgis.Warning)
        else:
            print(">>> self.on_found is None")

        # Restore previous map tool
        if getattr(self, "prev_map_tool", None):
            try:
                self.canvas.setMapTool(self.prev_map_tool)
            except Exception:
                pass

        if self.btn_select:
            self.btn_select.setStyleSheet("")  # reset color

        # Restore button color
        self.reset_drawing()


    def _layer_from_id(self, layer_id):
        if not layer_id:
            return None
        layer = QgsProject.instance().mapLayer(layer_id)
        if not isinstance(layer, QgsVectorLayer):
            return None
        return layer

    def reset_drawing(self):
        self.drawing = False
        self.points = []

        if self.rubber:
            try:
                self.rubber.reset(QgsWkbTypes.PolygonGeometry)
            except Exception:
                self.rubber.reset()
            try:
                self.rubber.hide()
            except Exception:
                pass

    def highlight_feature(self, layer: QgsVectorLayer, feature, color: QColor, width=2):
        try:
            h = QgsHighlight(self.canvas, feature.geometry(), layer)
            h.setColor(color)
            h.setWidth(width)
            h.show()
            self.highlights.append(h)
        except Exception:
            pass

    def deactivate(self):
        self.clear_highlights()
        try:
            super().deactivate()
        except Exception:
            pass
        # Reset button color when tool is deactivated
        if hasattr(self, 'btn_select') and self.btn_select:
            self.btn_select.setStyleSheet("")

    def clear_highlights(self):
        for h in getattr(self, "highlights", []):
            try:
                h.hide()
            except Exception:
                pass
            try:
                h.deleteLater()
            except Exception:
                pass
        self.highlights = []

    def reset(self):
        self.drawing = False
        self.points = []
        self.clear_highlights()

        self.reset_drawing()

        if self.rubber:
            try:
                self.rubber.reset(QgsWkbTypes.PolygonGeometry)
            except Exception:
                self.rubber.reset()
            try:
                self.rubber.hide()
            except Exception:
                pass

